Homework15(001)
SergeyChuyko/iosSchool_HxH pull request #18
Opened 2023-12-23 14:34 UTC by SergeyChuyko

2023-12-24 09:01 UTC, vaganova-ann requested changes
1) Поправь везде Created by

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/ApiClient/PersonApiClient.swift
> +protocol EpisodeApiClient {
Файл должен называться так же, как класс в нем

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Models/Episode.swift
> +struct Episode: Decodable {
все ли тебе поля нужны здесь?

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Avatar/CabinetAvatarCell.swift
> +        section.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
если все 0, то можно эту строчку не писать

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Avatar/CabinetAvatarCell.swift
> +    @IBOutlet private weak var avatarImageView: UIImageView!
должен быть еще bottom констрейнт от большого image view к супервью

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/CabinetAssembly.swift
> +    func cabinetVC(unLogin: (() -> Void)?) -> CabinetViewController<CabinetViewImp>
может лучше везде назовем вместо unLogin logout

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/CabinetView.swift
> +
лишняя пустая строчка

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/CabinetView.swift
> +        at indexPath: IndexPath) -> UICollectionReusableView {
здесь неправильно по строчкам разнесено

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/CabinetViewController.swift
> +        view.backgroundColor = .red
почему .red?

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/CabinetViewController.swift
> +        let selectClosure: ((CoreCellInputData) -> Void)? = { [weak self] _ in
можно здесь в отдельную переменную не выносить

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/AppCoordinator.swift
> +        let cabinetVC = assembly.rootNavigationController()
вместо того, чтобы делать
 navigationController?.setNavigationBarHidden(true, animated: animated)
во вью контроллере, попробуй сделать просто 
tabVC.setViewControllers([navVC, cabinetsVC], animated: false)
то есть не надо создавать 
let cabinetVC = assembly.rootNavigationController()

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/CabinetViewData.swift
> +    let episodeExitData: CabinetExitCellData
разделяем строкой свойства и функции

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Date/CabinetDateCell.swift
> +class CabinetDateCell: UICollectionViewCell, CoreCellView {
давай попробуем эту ячейку сверстать универсальнее: белая вью, на ней левый лейбл "дата"/"цвет", справа стеквью, в котором лежит лейбл и вью с цветом, в зависимости от типа ячейки лейбл или цвет скрываются.
в секции иметь две ячейки

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Date/CabinetDateCellData.swift
> +    let date: String
сюда бы еще цвет передавать

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Exit/CabinetExitCell.swift
> +
лишняя пустая строчка

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonView.swift
> +        sections[index].updateCell(at: IndexPath(item: idx, section: 1), with: data)
в IndexPath(item: idx, section: 1) тоже вместо 1 используем index

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonView.swift
> +            indexPath: IndexPath(item: idx, section: 1)
и здесь тоже

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewController.swift
> +        imageService.getImage(url: imageUrl ?? "") { [weak self] image in
если imageUrl == nil то есть ли смысл делать запрос?

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewController.swift
> +                        with: PersonEpisodeCellData(
здесь можно было PersonEpisodeCellData на строчку следующу не переносить

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewController.swift
> +            self.dataProvider.episode(url: url) {[weak self]  episode, error in
пробел потерялся между { [

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewController.swift
> +                    print(error ?? "ERROR")
принты убираем

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewData.swift
>          self.episodeData = episodeUrl.compactMap { PersonEpisodeCellData(url: $0 )}
здесь лишний пробел между $0 и )}

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/Subviews/Avatar/PersonAvatarCell.swift
> +
нужен MARK

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/Subviews/Episode/PersonEpisodeCell.swift
> +        label.adjustsFontSizeToFitWidth = true
давай не будем эту настройку использовать, не по дизайну получается, пусть лейбл будет с нужным шрифтом, две строчки, обрезается, если не вошел текст
и нормальный размер текста для dateLabel

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/Subviews/Episode/PersonEpisodeCell.swift
> +
лишняя пустая строчка

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/Subviews/Episode/PersonEpisodeCell.swift
> +    @IBOutlet private weak var numberView: UIView!
как-то странно сверстано, numberLabel должен быть в numberView

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Splash/SplashViewController.swift
> +        Timer.scheduledTimer(withTimeInterval: 0.01, repeats: false) { [weak self] timer in
верни как было

2023-12-24 09:01 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/Subviews/Header/PersonHeaderView.swift
> +        header.contentInsets = NSDirectionalEdgeInsets(top: 0, leading: 0, bottom: 0, trailing: 0)
если нулевые, то можно не указывать

2023-12-24 14:23 UTC, SergeyChuyko commented on iosSchool_HxH/Modules/Cabinet/Avatar/CabinetAvatarCell.swift
> +    @IBOutlet private weak var avatarImageView: UIImageView!
Он присутствует

2023-12-24 14:32 UTC, SergeyChuyko commented on iosSchool_HxH/Modules/Cabinet/CabinetViewController.swift
> +        let selectClosure: ((CoreCellInputData) -> Void)? = { [weak self] _ in
Так я же дальше в rootView.update использую кложуру эту

2023-12-26 07:50 UTC, vaganova-ann requested changes

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/AppCoordinator.swift
>          }
проверь отступ у этой скобки и добавь пустые строки между функциями

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/AppCoordinator.swift
> +        let cabinetVC = assembly.rootNavigationController()
теперь можешь удалить функции с настройкой navigationController?.setNavigationBarHidden(true, animated: animated) и посмотреть, будет норм или нет

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Date/CabinetDateCell.swift
> +        labelSettings(label: cellView)
нейминг функции и параметра надо поправить

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Date/CabinetDateCell.swift
> +        guard inputData.date != nil else {
лучше if, и в обеих ветках условия нужно явно прописать для colorView и dateLabel, когда у них .isHidden = true а когда .isHidden = false

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Date/CabinetDateCell.swift
> +
лишняя пустая строчка

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Cabinet/Date/CabinetDateCell.swift
>  class CabinetDateCell: UICollectionViewCell, CoreCellView {
1) для вью, лежащих в стеквью, мы не назначаем никаких констрейнтов, кроме ширины и высоты (и то не всегда и не для лейблов)
2) textLabel и стеквью должен быть соеденен констрейнтом

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewController.swift
> +        guard let imageUrl = imageUrl, !imageUrl.isEmpty else {
а теперь, если у тебя imageUrl == nil, то не загрузятся эпизоды

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/PersonViewController.swift
> +                        idx: idx, with: PersonEpisodeCellData(
нет, я имелла ввиду
self.rootView.updateEpisode(
idx: idx, 
with: PersonEpisodeCellData(episode: episode )
)

2023-12-26 07:50 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Person/Subviews/Avatar/PersonAvatarCell.swift
> +    // MARK: - Functions
пустая строчка нужна между MARK и функциями

2023-12-27 04:51 UTC, vaganova-ann approved these changes

2023-12-27 06:27 UTC, merged