Third homework
SergeyChuyko/iosSchool_HxH pull request #5
Opened 2023-11-05 17:14 UTC by SergeyChuyko

2023-11-06 06:56 UTC, vaganova-ann requested changes

2023-11-06 06:56 UTC, vaganova-ann commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        let idCharacter = Int.random(in: 0...99)
здесь и далее убери переменные, которые используются один раз, замени их на вызов нужной функции внутри принта/комплишена/итд

2023-11-06 06:56 UTC, vaganova-ann commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        return { _ in
перепиши кложуру так, чтобы параметр пригодился

2023-11-06 08:12 UTC, SergeyChuyko commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        return { _ in
func generateNameTree() -> ((String) -> Void) {
        let characterName = generateCharacterName()
        return { name in
            print("Generated name: \(characterName), nickname: \(name)")
        }
    }

2023-11-06 08:12 UTC, SergeyChuyko commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        let idCharacter = Int.random(in: 0...99)
так я же итак испоьзую эту функцию чтобы вызывать ее в каждом Кложуре, а не писать заного этот код с рандомайзером чисел

2023-11-08 04:00 UTC, vaganova-ann requested changes

2023-11-08 04:00 UTC, vaganova-ann commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        let characterName = generateCharacterName()
characterName не нужен, можно сразу generateCharacterName в completion вызывать

2023-11-08 04:00 UTC, vaganova-ann commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +    func generateNameTwo(completion: () -> (String)) {
просмотрела прошлый раз, а где здесь используется completion?

2023-11-08 04:00 UTC, vaganova-ann commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        let characterName = generateCharacterName()
можно убрать characterName и return, и вместо name использовать $0

2023-11-08 04:00 UTC, vaganova-ann commented on iosSchool_HxH/Homeworks/FirstHomework.swift
> +        let characterName = generateCharacterName()
можно убрать characterName и return

2023-11-09 03:57 UTC, vaganova-ann approved these changes

2023-11-09 05:11 UTC, merged