Homework4(001)
SergeyChuyko/iosSchool_HxH pull request #7
Opened 2023-11-09 11:06 UTC by SergeyChuyko

2023-11-10 03:48 UTC, vaganova-ann requested changes

2023-11-10 03:48 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            (0..<1).map { _ in
По заданию нужно сгенерировать трех персонажей

2023-11-10 03:48 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            (0..<1).compactMap { _ in
По заданию нужно сгенерировать трех персонажей

2023-11-10 03:48 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            return result + character.name.count
давай заменим result и character на $0 и $1

2023-11-10 03:48 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +        for _ in 1...10 {
замени здесь на map

2023-11-10 04:47 UTC, SergeyChuyko commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            (0..<1).map { _ in
Я прохожу по массиву episodeNames, и там как раз создается 3 персонажа

2023-11-10 04:47 UTC, SergeyChuyko commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            (0..<1).compactMap { _ in
Я прохожу по массиву episodeNames, и там как раз создается 3 персонажа

2023-11-11 11:23 UTC, vaganova-ann requested changes

2023-11-11 11:23 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            return characterGenerator.generateSomeCharacter()
return можно убрать

2023-11-11 11:24 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Auth/AuthViewController.swift
> +            (0..<1).map { _ in
а зачем тогда вообще эта конструкция здесь и в другом месте? по сути ты один раз вызываешь characterGenerator.generateSomeCharacter(), это можно делать и без (0..<1).map { _ in

2023-11-11 14:24 UTC, vaganova-ann approved these changes

2023-11-11 14:29 UTC, merged