Homework6(001)
SergeyChuyko/iosSchool_HxH pull request #9
Opened 2023-11-15 14:20 UTC by SergeyChuyko

2023-11-15 15:38 UTC, vaganova-ann requested changes

2023-11-15 15:38 UTC, vaganova-ann commented on iosSchool_HxH/AppCoordinator.swift
> +        setRoot(viewController: assembly.registrationVC(onRegistrationSuccess: {
сомнительно и не окей
ты уже делаешь показ registrationV, когда на 22 строчке делаешь setRoot(viewController: coordinator.make()), эта функция в целом странная и ненужная, достаточно было вместо ее вызова на 20 строке сделать print

2023-11-15 15:38 UTC, vaganova-ann commented on iosSchool_HxH/Modules/Registration/RegistrationViewController.swift
> +        self.onRegistrationSuccess?()
self не нужен

2023-11-15 15:49 UTC, SergeyChuyko commented on iosSchool_HxH/AppCoordinator.swift
> +        setRoot(viewController: assembly.registrationVC(onRegistrationSuccess: {
Тоесть мне не надо делать рутовый VC ?
Просто с черным экраном оставить и принтом проверить что кложурка прокидывается?

2023-11-18 10:15 UTC, vaganova-ann approved these changes

2023-11-18 11:28 UTC, merged